package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Genre;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface GenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    int insert(Genre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    Genre selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    List<Genre> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    int updateByPrimaryKey(Genre record);
}