package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.SongGenre;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface SongGenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG_GENRE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    int deleteByPrimaryKey(@Param("songsId") Integer songsId, @Param("genresId") Integer genresId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG_GENRE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    int insert(SongGenre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG_GENRE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    List<SongGenre> selectAll();
}