package lt.vu.mybatis.model;

public class Musician {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MUSICIAN.ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MUSICIAN.STAGENAME
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    private String stagename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MUSICIAN.ID
     *
     * @return the value of PUBLIC.MUSICIAN.ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MUSICIAN.ID
     *
     * @param id the value for PUBLIC.MUSICIAN.ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MUSICIAN.STAGENAME
     *
     * @return the value of PUBLIC.MUSICIAN.STAGENAME
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public String getStagename() {
        return stagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MUSICIAN.STAGENAME
     *
     * @param stagename the value for PUBLIC.MUSICIAN.STAGENAME
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public void setStagename(String stagename) {
        this.stagename = stagename;
    }
}