package lt.vu.mybatis.model;

public class SongGenre {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG_GENRE.SONGS_ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    private Integer songsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG_GENRE.GENRES_ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    private Integer genresId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG_GENRE.SONGS_ID
     *
     * @return the value of PUBLIC.SONG_GENRE.SONGS_ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public Integer getSongsId() {
        return songsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG_GENRE.SONGS_ID
     *
     * @param songsId the value for PUBLIC.SONG_GENRE.SONGS_ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public void setSongsId(Integer songsId) {
        this.songsId = songsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG_GENRE.GENRES_ID
     *
     * @return the value of PUBLIC.SONG_GENRE.GENRES_ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public Integer getGenresId() {
        return genresId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG_GENRE.GENRES_ID
     *
     * @param genresId the value for PUBLIC.SONG_GENRE.GENRES_ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public void setGenresId(Integer genresId) {
        this.genresId = genresId;
    }
}