package lt.vu.mybatis.model;

import java.util.Date;

public class Song {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.RELEASEDATE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    private Date releasedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.TITLE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ALBUM_ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    private Integer albumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.MUSICIAN_ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    private Integer musicianId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ID
     *
     * @return the value of PUBLIC.SONG.ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ID
     *
     * @param id the value for PUBLIC.SONG.ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.RELEASEDATE
     *
     * @return the value of PUBLIC.SONG.RELEASEDATE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public Date getReleasedate() {
        return releasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.RELEASEDATE
     *
     * @param releasedate the value for PUBLIC.SONG.RELEASEDATE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public void setReleasedate(Date releasedate) {
        this.releasedate = releasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.TITLE
     *
     * @return the value of PUBLIC.SONG.TITLE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.TITLE
     *
     * @param title the value for PUBLIC.SONG.TITLE
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ALBUM_ID
     *
     * @return the value of PUBLIC.SONG.ALBUM_ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ALBUM_ID
     *
     * @param albumId the value for PUBLIC.SONG.ALBUM_ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.MUSICIAN_ID
     *
     * @return the value of PUBLIC.SONG.MUSICIAN_ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public Integer getMusicianId() {
        return musicianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.MUSICIAN_ID
     *
     * @param musicianId the value for PUBLIC.SONG.MUSICIAN_ID
     *
     * @mbg.generated Tue Apr 13 13:12:35 EEST 2021
     */
    public void setMusicianId(Integer musicianId) {
        this.musicianId = musicianId;
    }
}